baseURL = "/"
languageCode = "en-US"

title = "Hugo Learn Documentation"
theme = "hugo"
themesdir = "../.."
metaDataFormat = "yaml"

[params]
  editURL = "https://github.com/sweehua/hugo/edit/master/exampleSite/content/"
  description = "SH's Page"
  author = "SweeHua"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]
